[IMPROVEMENT] - ESLint and New README
betrybe/sd-0x-project-movie-cards-library pull request #13
Opened 2020-11-04 12:18 UTC by LizzardMedeiros

2020-11-09 11:59 UTC, albertosca commented on package.json
> +    "eslint": "^6.8.0",
```suggestion
    "eslint": "6.8.0",
```

2020-11-09 12:01 UTC, albertosca commented on README.md
> +- [Lista de requisitos](#lista-de-requisitos)
Era legal cada requisito estar no sumário tbm!

2020-11-09 12:01 UTC, albertosca commented on README.md
> +## Depois de terminar o desenvolvimento (opcional)
Caixa alta aqui!

2020-11-09 12:01 UTC, albertosca commented on README.md
> +## Durante o desenvolvimento
Caixa alta aqui!

2020-11-09 12:02 UTC, albertosca reviewed
Tem que ajustar o arquivo `main.yml` pra usar o eslint!

2020-11-09 20:27 UTC, albertosca requested changes
Precisa também:

- [ ] Renomear a seção `## Desenvolvimento e testes` para `## REQUISITOS DO PROJETO`

2020-11-09 20:27 UTC, albertosca commented on README.md
> +* Criar aplicações completas de front-end utilizando a biblioteca React.
```suggestion
## HABILIDADES

* Saber a melhor forma para instalar um gerenciador de pacotes.

* Inicializar um projeto em React

* Utilizar JSX no React

* Utilizar o ReactDOM.render para renderizar elementos numa página web.

* Utilizar o import para usar código externo junto ao seu.

* Criar componentes React corretamente;

* Fazer uso de props corretamente;

* Fazer composição de componentes corretamente;

* Criar múltiplos componentes dinamicamente.

* Utilizar PropTypes para checar o tipo de uma prop no uso de um componente;

* Utilizar PropTypes para garantir a presença de props obrigatórias no uso de um componente;

* Utilizar PropTypes para checar que uma prop é um objeto de formato específico;

* Utilizar PropTypes para garantir que uma prop é um array com elementos de um determinado tipo.
```

Aqui são as habilidades de todos os dias do bloco! Sacou?

2020-11-09 20:27 UTC, albertosca commented on README.md
>  ## O que deverá ser desenvolvido
```suggestion
## O QUE DEVERÁ SER DESENVOLVIDO
```

E tem que jogar essa seção pra cima da `DATA DE ENTREGA`, pra ficar como está [nesse repo](https://github.com/tryber/sd-06-project-trivia-react-redux)! Rola?

2020-11-09 20:27 UTC, albertosca commented on README.md
> +
```suggestion
## DATA DE ENTREGA

* Projeto em grupo.

* Serão cinco dias de projeto.

* O projeto tem até a seguinte data: dd/mm/yyyy - 14:00h para ter entregue a avaliação final.

```

2020-11-09 20:27 UTC, albertosca commented on README.md
> +## Antes de começar a desenvolver
```suggestion
## COMO DESENVOLVER
### Antes de começar a desenvolver
```

2020-11-09 20:27 UTC, albertosca commented on README.md
> +O projeto deverá ser entregue até a seguinte data para a avaliação final: ``DD/MM/YYYY - 00:00h``.
```suggestion
```

Sugeri acrescentar essa seção lá em cima, aí acho que podemos remover ela daqui!

2020-11-09 20:27 UTC, albertosca commented on README.md
> +## REQUISITOS DO PROJETO
```suggestion
```

Colocando esse título lá em cima podemos arrancar ele daqui!

2020-11-09 20:27 UTC, albertosca commented on README.md
> +Todos os compontens que recebem props devem ter suas proptypes corretamente declaradas. O eslint checa automaticamente declaração de proptypes, portanto seu Pull Request deverá passar nas regras do e
```suggestion
Todos os compontens que recebem props devem ter suas PropTypes corretamente declaradas. O ESLint checa automaticamente declaração de PropTypes, portanto seu Pull Request deverá passar nas regras do ESLint para satisfazer esse requisito.
```

2020-11-09 20:27 UTC, albertosca commented on README.md
> +## LISTA DE REQUISITOS
Em _todos_ os requisitos precisamos colocar:

- [ ] Lista de especificações do avaliador, pra ele aprovar o requisito, numa seção `Observações técnicas`
- [ ] Texto discriminado dos `it`s de cada requisito, se houver algum, numa seção `O que será avaliado`

2020-11-09 20:28 UTC, albertosca commented on README.md
> +## DURANTE O DESENVOLVIMENTO
```suggestion
## Instruções para entregar seu projeto
### DURANTE O DESENVOLVIMENTO
```

2020-11-09 20:30 UTC, albertosca commented on src/App.test.js
> +  it('`App` deve renderizar `MovieList`', () => {
Nos its hora os componentes tem crases em volta e hora não. É melhor setar um padrão e seguir!
Eu acho melhor sem, não sei se as crases dão problema na hora de imprimir o que está errado no avaliador 🤔

2020-11-12 13:13 UTC, LizzardMedeiros commented on .trybe/requirements.json
> +    "bonus": true
Está certo, são 5 requisitos além dos subrequisitos

2020-11-12 13:16 UTC, closed without merging