Readme Update and Stylelint/ESLint implementantion
betrybe/sd-0x-project-movie-cards-library pull request #16
Opened 2020-12-07 14:08 UTC by phelipe-ohlsen

Removed **CodeClimate**
Implemented **ESLint** and **Stylelint**
Updated _README.md_

2020-12-09 14:42 UTC, LizzardMedeiros requested changes

2020-12-09 14:42 UTC, LizzardMedeiros commented on .stylelintrc.json
> +  "plugins": [
```suggestion
  "plugins": ["stylelint-order"],
```

2020-12-09 14:42 UTC, LizzardMedeiros commented on .stylelintrc.json
> +		"stylelint-order"
```suggestion
```

2020-12-09 14:42 UTC, LizzardMedeiros commented on .stylelintrc.json
> +	],
```suggestion
```

2020-12-09 14:42 UTC, LizzardMedeiros commented on .trybe/requirements.json
> +}
```suggestion
}

```

2021-01-05 13:02 UTC, LizzardMedeiros requested changes

2021-01-05 13:02 UTC, LizzardMedeiros commented on README.md
> +## Dica: desativanto testes
```suggestion
## Dica: desativando testes
```

2021-01-05 13:02 UTC, LizzardMedeiros commented on README.md
> +  - [Dica: desativanto testes](#dica-desativanto-testes)
```suggestion
  - [Dica: desativando testes](#dica-desativando-testes)
```

2021-01-12 20:19 UTC, albertosca approved these changes

2021-01-13 11:58 UTC, LizzardMedeiros approved these changes

2021-01-13 12:44 UTC, merged